# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927cb40c9237d0241743d03d53b9cfd351d8609e9134a73d68ab49501a6816a9ed15abb3047ca5202596dcc8c86ba5837e5429256a87c04ee44ae86c12f8f136

test:
  secret_key_base: 612bc66a78b98065bb75e984142352b34b39bf62114f38ace7ccfb460107a650995e2047b75835b183dfb03658378db2061ce247ccc124e7d11f67da5802c0a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
